// <auto-generated />
using Hrms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Hrms.Infrastructure.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    [Migration("20260618120000_RefactorRoleLabels")]
    partial class RefactorRoleLabels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot managed separately in HrmsDbContextModelSnapshot.cs
        }
    }
}
