// <auto-generated />
using System;
using Hrms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hrms.Infrastructure.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    [Migration("20260611041751_AddEmployeePasswordHash")]
    partial class AddEmployeePasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hrms.Domain.Entities.AttendanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckInAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_in_at");

                    b.Property<decimal?>("CheckInLat")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("check_in_lat");

                    b.Property<decimal?>("CheckInLng")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("check_in_lng");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_out_at");

                    b.Property<decimal?>("CheckOutLat")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("check_out_lat");

                    b.Property<decimal?>("CheckOutLng")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("check_out_lng");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsLate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_late");

                    b.Property<string>("SelfieUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("selfie_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("WorkMinutes")
                        .HasColumnType("int")
                        .HasColumnName("work_minutes");

                    b.HasKey("Id")
                        .HasName("pk_attendance_logs");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_attendance_logs_employee_id");

                    b.ToTable("attendance_logs", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsHrManagedByParent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hr_managed_by_parent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("OrgType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("org_type");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_id");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tax_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_companies_parent_id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeptType")
                        .HasColumnType("longtext")
                        .HasColumnName("dept_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentDeptId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_dept_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_departments_company_id");

                    b.HasIndex("ParentDeptId")
                        .HasDatabaseName("ix_departments_parent_dept_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("line_user_id");

                    b.Property<string>("NationalId")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("national_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_employees_company_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_employee_code");

                    b.HasIndex("LineUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_line_user_id");

                    b.HasIndex("NationalId")
                        .HasDatabaseName("ix_employees_national_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.EmployeeRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("department_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("granted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_employee_roles");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_employee_roles_company_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employee_roles_department_id");

                    b.HasIndex("EmployeeId", "Role", "CompanyId", "IsActive")
                        .HasDatabaseName("ix_employee_roles_employee_id_role_company_id_is_active");

                    b.ToTable("employee_roles", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.LeaveBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("leave_type_id");

                    b.Property<decimal>("PendingDays")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("pending_days");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("total_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("used_days");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_leave_balances");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("ix_leave_balances_leave_type_id");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_leave_balances_employee_id_leave_type_id_year");

                    b.ToTable("leave_balances", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("attachment_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.Property<string>("HalfDay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("half_day");

                    b.Property<DateTime?>("HrApprovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("hr_approved_at");

                    b.Property<string>("HrComment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("hr_comment");

                    b.Property<Guid?>("HrId")
                        .HasColumnType("char(36)")
                        .HasColumnName("hr_id");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SupervisorApprovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("supervisor_approved_at");

                    b.Property<string>("SupervisorComment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("supervisor_comment");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("supervisor_id");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("total_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_leave_requests");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("ix_leave_requests_leave_type_id");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_leave_requests_employee_id_status");

                    b.HasIndex("Status", "SupervisorId")
                        .HasDatabaseName("ix_leave_requests_status_supervisor_id");

                    b.ToTable("leave_requests", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<int>("DefaultDaysPerYear")
                        .HasColumnType("int")
                        .HasColumnName("default_days_per_year");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name_th");

                    b.Property<bool>("RequiresAttachment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_attachment");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_leave_types");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_leave_types_company_id");

                    b.ToTable("leave_types", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("EmployeeId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_employee_id_revoked_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Hrms.Domain.Entities.AttendanceLog", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Employee", "Employee")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_logs_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Company", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Company", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_companies_companies_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Department", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departments_companies_company_id");

                    b.HasOne("Hrms.Domain.Entities.Department", "ParentDept")
                        .WithMany()
                        .HasForeignKey("ParentDeptId")
                        .HasConstraintName("fk_departments_departments_parent_dept_id");

                    b.Navigation("Company");

                    b.Navigation("ParentDept");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_companies_company_id");

                    b.HasOne("Hrms.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.EmployeeRole", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_employee_roles_companies_company_id");

                    b.HasOne("Hrms.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_employee_roles_departments_department_id");

                    b.HasOne("Hrms.Domain.Entities.Employee", "Employee")
                        .WithMany("Roles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_roles_employees_employee_id");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.LeaveBalance", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_balances_employees_employee_id");

                    b.HasOne("Hrms.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_balances_leave_types_leave_type_id");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_requests_employees_employee_id");

                    b.HasOne("Hrms.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_requests_leave_types_leave_type_id");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.LeaveType", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leave_types_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Hrms.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Company", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Hrms.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
