using Hrms.Domain.Enums;

namespace Hrms.Application.Features.Tickets.Dtos;

public record TicketDto(
    Guid Id,
    string TicketNo,
    TicketRequestType RequestType,
    Guid? RequesterEmployeeId,
    string RequesterName,
    TicketRequesterDto Requester,
    Guid? SourceCompanyId,
    Guid? SourceDepartmentId,
    Guid TargetCompanyId,
    string TargetCompanyName,
    Guid? TargetDepartmentId,
    string? TargetDepartmentName,
    Guid? CategoryId,
    string? CategoryName,
    Guid? TopicId,
    string? TopicName,
    Guid? SubjectId,
    string? SubjectName,
    Guid? ExternalTicketCategoryId,
    string? ExternalTicketCategoryName,
    Guid? ExternalTicketTopicId,
    string? ExternalTicketTopicName,
    Guid? ExternalTicketSubjectId,
    string? ExternalTicketSubjectName,
    string? OtherTopicText,
    string Title,
    string Detail,
    TicketPriority Priority,
    TicketStatus Status,
    Guid? WorkflowDefinitionId,
    string? WorkflowName,
    int? WorkflowAutoAcknowledgeAfterDays,
    IReadOnlyList<TicketWorkflowStepDto> WorkflowSteps,
    IReadOnlyDictionary<TicketStatus, int> WorkflowCurrentStepIndexByStatus,
    Guid? SubjectGuidanceConfigId,
    string? SubjectGuidanceConfigName,
    string? VehicleText,
    string? LocationText,
    string? ContactPhone,
    string? ContactNote,
    IReadOnlyList<TicketAttachmentDto> Attachments,
    DateTime CreatedAt,
    TicketRoutingSummaryDto RoutingResult);

public record TicketRoutingSummaryDto(
    TicketRoutingMode Mode,
    TicketRoutingLevel Level,
    TicketRoutingOutcome Outcome,
    Guid? AssigneeId,
    string? AssigneeName);
